Repository SOPT-all/35-COLLABORATION-iOS-YES24TICKET, pull requests merged in 2024-11, with the labels that each got.

#2 프로젝트 세팅
  .gitignore
  Yes24Ticket/Yes24Ticket.xcodeproj/project.pbxproj
  Yes24Ticket/Yes24Ticket.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Yes24Ticket/Yes24Ticket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Yes24Ticket/Yes24Ticket.xcodeproj/xcshareddata/xcschemes/Yes24Ticket.xcscheme
  Yes24Ticket/Yes24Ticket/Application/AppDelegate.swift
  Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
  Yes24Ticket/Yes24Ticket/Presentation/Category/CategoryViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/MyPage/MyPageViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Search/SearchViewController.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Temp.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Temp.imageset/Frame 11.png
  Yes24Ticket/Yes24Ticket/Resources/Base.lproj/LaunchScreen.storyboard
  Yes24Ticket/Yes24Ticket/Resources/Info.plist
Labels: 📄 docs, 📁 build, 🟣 성민's code

#8 기본 Color 네이밍과 겹치는 경고 해결
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Color/black0.colorset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Color/white0.colorset/Contents.json
Labels: ⚙️ fix, 🟣 성민's code

#6 탭바 구현
  Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarController.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarItem.swift
Labels: 🎫 feat, 🟣 성민's code

#10 네트워크 레이어 구현
  .gitignore
  Yes24Ticket/Yes24Ticket.xcodeproj/project.pbxproj
  Yes24Ticket/Yes24Ticket/Network/APIService.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Request/RequestExampleDTO.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/ResponseExampleDTO.swift
  Yes24Ticket/Yes24Ticket/Network/Error/ExampleError.swift
  Yes24Ticket/Yes24Ticket/Network/Error/RouterError.swift
  Yes24Ticket/Yes24Ticket/Network/Router/DefaultRouter.swift
  Yes24Ticket/Yes24Ticket/Network/Router/Protocol/Router.swift
  Yes24Ticket/Yes24Ticket/Network/Util/Encodable+Dictionary.swift
  Yes24Ticket/Yes24Ticket/Network/Util/Environement.swift
  Yes24Ticket/Yes24Ticket/Resources/Info.plist
Labels: 🎫 feat, 📁 build, 🟣 성민's code

#15 열린 검색바 구현
  Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/SearchBarView.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarController.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarItem.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarNavigationController.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Color/white_dim.colorset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Component/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Component/logo_yes24_ios.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Component/logo_yes24_ios.imageset/logo_yes24_ios.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Component/logo_yes24_ios.imageset/logo_yes24_ios@2x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Component/logo_yes24_ios.imageset/logo_yes24_ios@3x.png
Labels: 🎫 feat, ♻️ chore, 🟣 성민's code

#16 상세정보 네비게이션 바 구현
  Yes24Ticket/Yes24Ticket.xcodeproj/project.pbxproj
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailViewController.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/_btn_floating_30.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/_btn_floating_30.imageset/_btn_floating_30.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array1.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array1.imageset/btn_a_array1.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array1_select.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array1_select.imageset/btn_a_array1_select.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array2.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array2.imageset/btn_a_array2.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array3.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array3.imageset/btn_a_array3.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array4.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_array4.imageset/btn_a_array4.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_text_arrow_right_red.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_a_text_arrow_right_red.imageset/btn_a_text_arrow_right_red.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_array_a.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_array_a.imageset/btn_array_a.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_array_select_a.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_array_select_a.imageset/btn_array_select_a.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_ apply_a.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_ apply_a.imageset/btn_pop_ apply_a.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_a.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_a.imageset/btn_pop_a.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_select_a.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/btn_pop_select_a.imageset/btn_pop_select_a.svg
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/cmp_exclusive.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/cmp_exclusive.imageset/cmp_exclusive.svg
Labels: 🎫 feat, 🟢 여경's code

#14 Footer 구현
  Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/divider.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/divider.imageset/Vector 34.svg
  Yes24Ticket/Yes24Ticket/Resources/Info.plist
Labels: 🎫 feat, 🔵 어진's code

#20 메인 구현
  Yes24Ticket/Yes24Ticket.xcodeproj/project.pbxproj
  Yes24Ticket/Yes24Ticket/Model/MainCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/MainCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/MainFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Util/UICollectionReusableView+Identifier.swift
  Yes24Ticket/Yes24Ticket/Presentation/Util/UICollectionViewCell+Identifier.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_gd.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_gd.imageset/Rectangle 786.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_gd.imageset/Rectangle 786@2x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_gd.imageset/Rectangle 786@3x.png
Labels: 🎫 feat, 🟣 성민's code

#24 닫힌 검색바 구현
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/ClosedSearchBarView.swift
Labels: 🎫 feat, 🔵 어진's code

#26 실시간 티켓랭킹 구현
  Yes24Ticket/Yes24Ticket/Model/TicketRankConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/TicketRankCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/TicketRankFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/TicketRankHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/TicketRankSectionBackgroundView.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_mini_gd.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_mini_gd.imageset/black_mini_gd.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_mini_gd.imageset/black_mini_gd@2x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/Gradation/black_mini_gd.imageset/black_mini_gd@3x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/icn_blueArrow.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/icn_blueArrow.imageset/icn_blueArrow.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/icn_blueArrow.imageset/icn_blueArrow@2x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/icon/icn_blueArrow.imageset/icn_blueArrow@3x.png
Labels: 🎫 feat, 🟣 성민's code

#25 티켓 정보 구현
  Yes24Ticket/Yes24Ticket/Network/APIService.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/Model/Concert.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Util/UIFont+.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/white_gd.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/white_gd.imageset/Rectangle 786.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/white_gd.imageset/Rectangle 786@2x.png
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/white_gd.imageset/Rectangle 786@3x.png
Labels: 🎫 feat, 🟢 여경's code

#28 광고 배너 구현
  Yes24Ticket/Yes24Ticket/Model/AdCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/TicketRankCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/AdCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/IndexBadgeFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/TicketRankCollectionViewCell.swift
Labels: 🎫 feat, 🟣 성민's code

#31 콘서트 네비게이션바 구현
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/ClosedSearchBarView.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/ConcertNavigationBar.swift
Labels: 🎫 feat, 🔵 어진's code

#33 WHAT'S HOT 구현
  Yes24Ticket/Yes24Ticket/Model/WhatsHotCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/WhatsHotCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/WhatsHotHeaderView.swift
Labels: 🎫 feat, 🟣 성민's code

#34 티켓 상세 정보 구현
  Yes24Ticket/Yes24Ticket/Model/ConcertConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/HeaderDetailView.swift
  Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/TicketDetailView.swift
Labels: 🎫 feat, 🟢 여경's code

#39 홈 뷰 연결 및 완성
  Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
  Yes24Ticket/Yes24Ticket/Presentation/Common/FooterReusableView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/IndexBadgeFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/WhatsHotHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarController.swift
Labels: 🎫 feat, 🛠️ refactor, 🟣 성민's code

#40 콘서트 탭 컨트롤러 구현
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
Labels: 🎫 feat, 🔵 어진's code

#42 API 연결
  Yes24Ticket/Yes24Ticket/Model/AdCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/CategoryCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/MainCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/TicketRankCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/WhatsHotCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Model/WithURL/AdCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Model/WithURL/MainCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Model/WithURL/TicketRankCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Model/WithURL/WhatsHotCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Network/APIService.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/ADsDTO.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/MainTicketsDTO.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/RankListDTO.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/ResponseExampleDTO.swift
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/WhatsHotTicketsDTO.swift
  Yes24Ticket/Yes24Ticket/Network/Error/FetchMainError.swift
  Yes24Ticket/Yes24Ticket/Network/Router/DefaultRouter.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/HomeViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/IndexBadgeFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/TabBar/TabBarController.swift
  Yes24Ticket/Yes24Ticket/Resources/Info.plist
Labels: 🎫 feat, ⚙️ fix, 🛠️ refactor, 🟣 성민's code

#44 상단 이동 플로팅 버튼 구현
  Yes24Ticket/Yes24Ticket/Presentation/Common/ScrollUpFloatingButton.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/AdCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/CategoryCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/MainCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/TicketRankCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/WhatsHotCellConfiguration.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/WithURL/AdCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/WithURL/MainCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/WithURL/TicketRankCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/Model/WithURL/WhatsHotCellConfigurationWithURL.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Cell/AdCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Cell/CategoryCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Cell/MainCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Cell/TicketRankCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Cell/WhatsHotCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Decoration/TicketRankSectionBackgroundView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Header/IndexBadgeFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Header/TicketRankFooterView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Header/TicketRankHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/View/Header/WhatsHotHeaderView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎫 feat, 🟣 성민's code

#45 콘서트 카테고리 뷰 구현
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertModel.swift
Labels: 🎫 feat, 🔵 어진's code

#49 인기순 정렬 바텀시트 구현
  Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/kim.imageset/Contents.json
  Yes24Ticket/Yes24Ticket/Resources/Assets.xcassets/kim.imageset/스크린샷 2024-11-29 오후 2.35.02.png
Labels: 🎫 feat, 🔵 어진's code

#51 콘서트 카테고리뷰 API 연결
  Yes24Ticket/Yes24Ticket/Network/DTO/Response/ConcertDTO.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
  Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertModel.swift
Labels: 🎫 feat, 🔵 어진's code
